template = "https://github.com/giellalt/template-lang-und"
rev_id = 330
template_sha = "ca06c138bb7dc0942a15e60b710a001352e6ebde"

[replacements]
__GLOTTOLOG_ID__ = "oroh1237"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-ora"
__UND2C__ = "ora"
__UNDEFINED__ = "Oroha"
__UND__ = "ora"
