template = "https://github.com/giellalt/template-lang-und"
rev_id = 294
template_sha = "a620868b33dee503846060f7bd6c6e88f3c1f6d1"

[replacements]
__GLOTTOLOG_ID__ = "oroh1237"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-ora"
__UND2C__ = "ora"
__UNDEFINED__ = "Oroha"
__UND__ = "ora"
