template = "https://github.com/giellalt/template-lang-und"
rev_id = 280
template_sha = "6beee360d8349c39749ac477719ead241493924c"

[replacements]
__GLOTTOLOG_ID__ = "oroh1237"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-ora"
__UND2C__ = "ora"
__UNDEFINED__ = "Oroha"
__UND__ = "ora"
