template = ""
rev_id = 190
template_sha = "8af7b46aad216e2fd14899eecebc0a4d246e2e41"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-ora"
__UND2C__ = "ora"
__UNDEFINED__ = "Oroha"
__UND__ = "ora"
